# 导入第三方包

In [3]:
import os
import gc
import math

import pandas as pd
import numpy as np

import lightgbm as lgb
import xgboost as xgb
from catboost import CatBoostRegressor
from sklearn.linear_model import SGDRegressor, LinearRegression, Ridge
from sklearn.preprocessing import MinMaxScaler


from sklearn.model_selection import StratifiedKFold, KFold
from sklearn.metrics import log_loss
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import OneHotEncoder

from tqdm import tqdm
import matplotlib.pyplot as plt
import time
import warnings
warnings.filterwarnings('ignore')

# 读取数据

In [5]:
train = pd.read_csv('train.csv')
test=pd.read_csv('testA.csv')
train.head()

id                                  heartbeat_signals  label
0   0  0.9912297987616655,0.9435330436439665,0.764677...    0.0
1   1  0.9714822034884503,0.9289687459588268,0.572932...    0.0
2   2  1.0,0.9591487564065292,0.7013782792997189,0.23...    2.0
3   3  0.9757952826275774,0.9340884687738161,0.659636...    0.0
4   4  0.0,0.055816398940721094,0.26129357194994196,0...    2.0

In [6]:
test.head()

id                                  heartbeat_signals
0  100000  0.9915713654170097,1.0,0.6318163407681274,0.13...
1  100001  0.6075533139615096,0.5417083883163654,0.340694...
2  100002  0.9752726292239277,0.6710965234906665,0.686758...
3  100003  0.9956348033996116,0.9170249621481004,0.521096...
4  100004  1.0,0.8879490481178918,0.745564725322326,0.531...

# 数据预处理

In [7]:
def reduce_mem_usage(df):
    start_mem = df.memory_usage().sum() / 1024**2 
    print('Memory usage of dataframe is {:.2f} MB'.format(start_mem))
    
    for col in df.columns:
        col_type = df[col].dtype
        
        if col_type != object:
            c_min = df[col].min()
            c_max = df[col].max()
            if str(col_type)[:3] == 'int':
                if c_min > np.iinfo(np.int8).min and c_max < np.iinfo(np.int8).max:
                    df[col] = df[col].astype(np.int8)
                elif c_min > np.iinfo(np.int16).min and c_max < np.iinfo(np.int16).max:
                    df[col] = df[col].astype(np.int16)
                elif c_min > np.iinfo(np.int32).min and c_max < np.iinfo(np.int32).max:
                    df[col] = df[col].astype(np.int32)
                elif c_min > np.iinfo(np.int64).min and c_max < np.iinfo(np.int64).max:
                    df[col] = df[col].astype(np.int64)  
            else:
                if c_min > np.finfo(np.float16).min and c_max < np.finfo(np.float16).max:
                    df[col] = df[col].astype(np.float16)
                elif c_min > np.finfo(np.float32).min and c_max < np.finfo(np.float32).max:
                    df[col] = df[col].astype(np.float32)
                else:
                    df[col] = df[col].astype(np.float64)
        else:
            df[col] = df[col].astype('category')

    end_mem = df.memory_usage().sum() / 1024**2 
    print('Memory usage after optimization is: {:.2f} MB'.format(end_mem))
    print('Decreased by {:.1f}%'.format(100 * (start_mem - end_mem) / start_mem))
    
    return df

In [8]:
# 简单预处理
train_list = []

for items in train.values:
    train_list.append([items[0]] + [float(i) for i in items[1].split(',')] + [items[2]])

train = pd.DataFrame(np.array(train_list))
train.columns = ['id'] + ['s_'+str(i) for i in range(len(train_list[0])-2)] + ['label']
train = reduce_mem_usage(train)

test_list=[]
for items in test.values:
    test_list.append([items[0]] + [float(i) for i in items[1].split(',')])

test = pd.DataFrame(np.array(test_list))
test.columns = ['id'] + ['s_'+str(i) for i in range(len(test_list[0])-1)]
test = reduce_mem_usage(test)


Memory usage of dataframe is 157.93 MB
Memory usage after optimization is: 39.67 MB
Decreased by 74.9%
Memory usage of dataframe is 31.43 MB
Memory usage after optimization is: 7.90 MB
Decreased by 74.9%


In [9]:
train.head()

id       s_0       s_1       s_2       s_3       s_4       s_5       s_6  \
0  0.0  0.991211  0.943359  0.764648  0.618652  0.379639  0.190796  0.040222   
1  1.0  0.971680  0.929199  0.572754  0.178467  0.122986  0.132324  0.094421   
2  2.0  1.000000  0.958984  0.701172  0.231812  0.000000  0.080688  0.128418   
3  3.0  0.975586  0.934082  0.659668  0.249878  0.237061  0.281494  0.249878   
4  4.0  0.000000  0.055817  0.261230  0.359863  0.433105  0.453613  0.499023   

        s_7       s_8  ...  s_196  s_197  s_198  s_199  s_200  s_201  s_202  \
0  0.026001  0.031708  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
1  0.089600  0.030487  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
2  0.187500  0.280762  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
3  0.249878  0.241455  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   
4  0.542969  0.616699  ...    0.0    0.0    0.0    0.0    0.0    0.0    0.0   

   s_203  s_204  label  
0    0.0    0.0    0.0  
1    0.0    0.0    0.0  
2    0.0    0.0    2.0  
3    0.0    0.0    0.0  
4    0.0    0.0    2.0  

[5 rows x 207 columns]

In [10]:
test.head()

id       s_0       s_1       s_2       s_3       s_4       s_5  \
0  100000.0  0.991699  1.000000  0.631836  0.136230  0.041412  0.102722   
1  100001.0  0.607422  0.541504  0.340576  0.000000  0.090698  0.164917   
2  100002.0  0.975098  0.670898  0.686523  0.708496  0.718750  0.716797   
3  100003.0  0.995605  0.916992  0.520996  0.000000  0.221802  0.404053   
4  100004.0  1.000000  0.888184  0.745605  0.531738  0.380371  0.224609   

        s_6       s_7       s_8  ...     s_195     s_196     s_197     s_198  \
0  0.120850  0.123413  0.107910  ...  0.000000  0.000000  0.000000  0.000000   
1  0.195068  0.168823  0.198853  ...  0.389893  0.386963  0.367188  0.364014   
2  0.720703  0.701660  0.596680  ...  0.000000  0.000000  0.000000  0.000000   
3  0.490479  0.527344  0.518066  ...  0.000000  0.000000  0.000000  0.000000   
4  0.091125  0.057648  0.003914  ...  0.000000  0.000000  0.000000  0.000000   

      s_199     s_200     s_201     s_202     s_203    s_204  
0  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  
1  0.360596  0.357178  0.350586  0.350586  0.350586  0.36377  
2  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  
3  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  
4  0.000000  0.000000  0.000000  0.000000  0.000000  0.00000  

[5 rows x 206 columns]

# 训练数据/测试数据准备

In [11]:
x_train = train.drop(['id','label'], axis=1)
y_train = train['label']
x_test=test.drop(['id'], axis=1)

# 模型训练

In [12]:
def abs_sum(y_pre,y_tru):
    y_pre=np.array(y_pre)
    y_tru=np.array(y_tru)
    loss=sum(sum(abs(y_pre-y_tru)))
    return loss
    

In [13]:
def cv_model(clf, train_x, train_y, test_x, clf_name):
    folds = 5
    seed = 2021
    kf = KFold(n_splits=folds, shuffle=True, random_state=seed)
    test = np.zeros((test_x.shape[0],4))

    cv_scores = []
    onehot_encoder = OneHotEncoder(sparse=False)
    for i, (train_index, valid_index) in enumerate(kf.split(train_x, train_y)):
        print('************************************ {} ************************************'.format(str(i+1)))
        trn_x, trn_y, val_x, val_y = train_x.iloc[train_index], train_y[train_index], train_x.iloc[valid_index], train_y[valid_index]
        
        if clf_name == "lgb":
            train_matrix = clf.Dataset(trn_x, label=trn_y)
            valid_matrix = clf.Dataset(val_x, label=val_y)

            params = {
                'boosting_type': 'gbdt',
                'objective': 'multiclass',
                'num_class': 4,
                'num_leaves': 2 ** 5,
                'feature_fraction': 0.8,
                'bagging_fraction': 0.8,
                'bagging_freq': 4,
                'learning_rate': 0.1,
                'seed': seed,
                'nthread': 28,
                'n_jobs':24,
                'verbose': -1,
            }

            model = clf.train(params, 
                      train_set=train_matrix, 
                      valid_sets=valid_matrix, 
                      num_boost_round=2000, 
                      verbose_eval=100, 
                      early_stopping_rounds=200)
            val_pred = model.predict(val_x, num_iteration=model.best_iteration)
            test_pred = model.predict(test_x, num_iteration=model.best_iteration) 
            
        val_y=np.array(val_y).reshape(-1, 1)
        val_y = onehot_encoder.fit_transform(val_y)
        print('预测的概率矩阵为：')
        print(test_pred)
        test += test_pred
        score=abs_sum(val_y, val_pred)
        cv_scores.append(score)
        print(cv_scores)
    print("%s_scotrainre_list:" % clf_name, cv_scores)
    print("%s_score_mean:" % clf_name, np.mean(cv_scores))
    print("%s_score_std:" % clf_name, np.std(cv_scores))
    test=test/kf.n_splits

    return test

In [14]:
def lgb_model(x_train, y_train, x_test):
    lgb_test = cv_model(lgb, x_train, y_train, x_test, "lgb")
    return lgb_test

In [15]:
lgb_test = lgb_model(x_train, y_train, x_test)

************************************ 1 ************************************
Training until validation scores don't improve for 200 rounds.
[100]	valid_0's multi_logloss: 0.0653424
[200]	valid_0's multi_logloss: 0.0455826
[300]	valid_0's multi_logloss: 0.0397864
[400]	valid_0's multi_logloss: 0.0383957
[500]	valid_0's multi_logloss: 0.0387627
[600]	valid_0's multi_logloss: 0.0401851
Early stopping, best iteration is:
[464]	valid_0's multi_logloss: 0.0381242
预测的概率矩阵为：
[[9.99971634e-01 2.76320644e-05 4.57591001e-07 2.76195523e-07]
 [6.34881589e-05 7.20448721e-04 9.99216047e-01 1.56497053e-08]
 [9.39312581e-07 4.40603086e-08 7.10995462e-07 9.99998306e-01]
 ...
 [5.88603696e-02 3.21619670e-04 9.40814937e-01 3.07401230e-06]
 [9.99970492e-01 2.94600453e-05 2.20294441e-08 2.59049471e-08]
 [9.90795237e-01 2.03516408e-03 5.48844645e-03 1.68115200e-03]]
[579.6590863493177]
************************************ 2 ************************************
Training until validation scores don't improve fo

In [16]:
lgb_test

array([[9.99968725e-01, 2.95265318e-05, 9.97267668e-07, 7.51544046e-07],
       [6.05062162e-05, 9.11792874e-04, 9.99027671e-01, 2.94782661e-08],
       [1.21443744e-06, 1.46948466e-07, 1.29543467e-06, 9.99997343e-01],
       ...,
       [3.74677912e-02, 3.43106904e-04, 9.62184648e-01, 4.45364686e-06],
       [9.99956993e-01, 4.28616241e-05, 5.23330316e-08, 9.31912512e-08],
       [9.18367847e-01, 8.88989418e-03, 6.32759128e-02, 9.46634589e-03]])

In [17]:
temp=pd.DataFrame(lgb_test)
temp

0             1             2             3
0      9.999687e-01  2.952653e-05  9.972677e-07  7.515440e-07
1      6.050622e-05  9.117929e-04  9.990277e-01  2.947827e-08
2      1.214437e-06  1.469485e-07  1.295435e-06  9.999973e-01
3      9.999600e-01  2.392160e-05  1.604452e-05  4.333388e-08
4      9.999834e-01  3.319449e-06  1.301041e-05  2.586476e-07
5      9.999800e-01  1.490246e-05  5.037220e-06  2.439451e-08
6      9.974892e-01  2.407864e-03  9.482934e-05  8.066644e-06
7      9.999388e-01  1.285062e-06  5.904354e-05  8.341002e-07
8      9.997668e-01  2.267033e-04  6.275459e-06  1.891242e-07
9      1.103043e-07  1.285512e-09  2.702164e-08  9.999999e-01
10     9.999565e-01  2.802787e-05  1.420977e-05  1.271939e-06
11     9.724950e-01  2.027333e-04  2.730187e-02  4.011321e-07
12     9.986327e-01  8.524262e-04  5.144210e-04  4.094865e-07
13     9.999248e-01  7.446956e-05  7.597951e-07  3.527185e-09
14     9.986005e-01  1.292273e-03  9.900627e-05  8.213938e-06
15     9.998670e-01  1.309447e-04  2.073586e-06  2.313842e-09
16     9.998735e-01  1.249926e-04  9.487264e-07  5.874773e-07
17     2.285781e-05  5.688484e-06  9.999639e-01  7.569212e-06
18     8.415080e-03  4.358958e-02  9.479902e-01  5.125701e-06
19     2.679511e-05  2.352655e-07  3.196213e-06  9.999698e-01
20     9.998688e-01  7.886619e-05  5.125282e-05  1.076655e-06
21     1.457258e-06  1.433102e-08  6.747477e-08  9.999985e-01
22     9.999522e-01  4.585858e-05  1.259776e-06  7.232906e-07
23     2.395382e-04  3.563065e-08  2.582875e-05  9.997346e-01
24     9.999869e-01  9.880815e-06  2.940517e-06  2.851246e-07
25     9.998881e-01  6.365898e-05  4.817893e-05  2.399756e-08
26     4.202544e-02  9.258983e-04  9.570423e-01  6.336088e-06
27     9.999275e-01  7.192772e-05  1.551479e-07  4.257051e-07
28     9.999522e-01  2.515031e-05  2.268067e-05  1.308123e-08
29     9.992967e-01  2.662579e-04  4.362835e-04  7.575660e-07
...             ...           ...           ...           ...
19970  8.977641e-07  3.511178e-09  1.652565e-08  9.999991e-01
19971  9.995993e-01  3.924162e-04  8.121822e-06  1.836850e-07
19972  1.629109e-07  5.665614e-09  1.773225e-06  9.999981e-01
19973  1.054219e-07  2.443637e-09  7.923158e-07  9.999991e-01
19974  2.545008e-05  1.654896e-04  9.998090e-01  3.185277e-08
19975  8.111937e-05  1.278232e-05  9.999055e-01  6.428445e-07
19976  9.975396e-01  4.058402e-04  1.987623e-03  6.691370e-05
19977  9.999723e-01  5.360684e-06  2.156446e-05  7.647779e-07
19978  1.934612e-03  4.951713e-07  9.372539e-05  9.979712e-01
19979  9.973332e-01  8.575510e-04  1.442632e-03  3.666160e-04
19980  5.675976e-05  3.008666e-04  9.996423e-01  7.776878e-08
19981  9.986805e-01  1.203451e-03  1.157016e-04  3.468475e-07
19982  8.034393e-04  2.402563e-05  9.991697e-01  2.801542e-06
19983  9.999574e-01  3.519065e-05  7.372603e-06  7.007502e-09
19984  2.888631e-01  7.111285e-01  8.243237e-06  1.446890e-07
19985  9.999897e-01  7.571042e-06  2.673729e-06  1.331461e-08
19986  9.999461e-01  3.722884e-06  3.872752e-05  1.147133e-05
19987  9.825803e-01  7.758706e-05  1.733716e-02  4.939849e-06
19988  9.999872e-01  1.265651e-05  1.216723e-07  7.190659e-09
19989  9.999861e-01  1.267847e-05  1.201049e-06  5.512190e-08
19990  9.981130e-01  1.884872e-03  1.786254e-06  3.391343e-07
19991  9.999787e-01  8.660803e-06  1.208434e-05  5.141085e-07
19992  9.999096e-01  8.725967e-05  4.973760e-07  2.661502e-06
19993  9.967611e-01  9.172758e-04  2.145070e-03  1.765148e-04
19994  9.999385e-01  4.691523e-06  5.217850e-05  4.605276e-06
19995  9.983211e-01  3.133803e-04  1.576273e-04  1.207908e-03
19996  9.998267e-01  1.575589e-04  1.560609e-05  1.227454e-07
19997  3.746779e-02  3.431069e-04  9.621846e-01  4.453647e-06
19998  9.999570e-01  4.286162e-05  5.233303e-08  9.319125e-08
19999  9.183678e-01  8.889894e-03  6.327591e-02  9.466346e-03

[20000 rows x 4 columns]

In [18]:
result=pd.read_csv('sample_submit.csv')
result['label_0']=temp[0]
result['label_1']=temp[1]
result['label_2']=temp[2]
result['label_3']=temp[3]
result.to_csv('submit.csv',index=False)